<!doctype html>
<html class="no-js" lang="">

<head>
<? include('partials/head.phtml');?>
</head>

<body class="page-loading">
<!-- page loading spinner -->
<div class="pageload">
    <div class="pageload-inner">
        <div class="sk-rotating-plane"></div>
    </div>
</div>
<!-- /page loading spinner -->
<div class="app layout-fixed-header">
    <!-- content panel -->
    <div>

        <!-- main area -->
        <div class="main-content">

            <img src="adminAssets/images/yetiweb.svg" class="installerLogo">

            <h3 class="text-center">Success</h3>
            <p class="text-center">Your website has now been installed and can be customised..</p>



        </div>
        <!-- /main area -->
    </div>
    <!-- /content panel -->
    <!-- bottom footer -->
    <footer class="content-footer">


    </footer>
    <!-- /bottom footer -->
</div>
<!-- build:js({.tmp,app}) scripts/app.min.js -->
<script src="adminAssets/scripts/helpers/modernizr.js"></script>
<script src="adminAssets/vendor/jquery/dist/jquery.js"></script>
<script src="adminAssets/vendor/bootstrap/dist/js/bootstrap.js"></script>
<script src="adminAssets/vendor/fastclick/lib/fastclick.js"></script>
<script src="adminAssets/vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
<script src="adminAssets/scripts/helpers/smartresize.js"></script>
<script src="adminAssets/scripts/constants.js"></script>
<script src="adminAssets/scripts/main.js"></script>
<!-- endbuild -->
</body>

</html>