<meta charset="utf-8">
<title>Yeti Media Group</title>
<meta name="description" content="">
<base href="/">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
<!-- build:css({.tmp,app}) styles/app.min.css -->
<link rel="stylesheet" href="adminAssets/vendor/summernote/dist/summernote.css">
<link rel="stylesheet" href="adminAssets/styles/webfont.css">
<link rel="stylesheet" href="adminAssets/styles/climacons-font.css">
<link rel="stylesheet" href="adminAssets/vendor/bootstrap/dist/css/bootstrap.css">
<link rel="stylesheet" href="adminAssets/styles/font-awesome.css">
<link rel="stylesheet" href="adminAssets/styles/card.css">
<link rel="stylesheet" href="adminAssets/styles/sli.css">
<link rel="stylesheet" href="adminAssets/styles/animate.css">
<link rel="stylesheet" href="adminAssets/styles/app.skins.css">
<link rel="stylesheet" href="adminAssets/styles/style.css">

<!-- endbuild -->